okay... ACTUALLY fixing it this time [#´Д`]

diff --git a/elysium b/elysium
--- a/elysium
+++ b/elysium
@@ -2,16 +2,22 @@
 Warn_Invalid="Invalid/unsupported driver selection!"
 if [[ "$(basename $0)" == "elysium" ]]; then
 	GPU="$1"
-	cmd="${@:2}"
+	case "$GPU" in
+		  elnvidiad|nvidia) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __VK_LAYER_NV_optimus=NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json __GLX_VENDOR_LIBRARY_NAME=nvidia LIBVA_DRIVER_NAME=nvidia VDPAU_DRIVER=nvidia "${@:2}" ;;
+		elnouveaud|nouveau) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __VK_LAYER_NV_optimus=NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nouveau_icd.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=nouveau VDPAU_DRIVER=nvidia "${@:2}" ;;
+			elamdd|amd) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=0 __VK_LAYER_NV_optimus=non_NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=radeon VDPAU_DRIVER=r600 "${@:2}" ;;
+		    elinteli|intel) DRI_PRIME=0 __NV_PRIME_RENDER_OFFLOAD=0 __VK_LAYER_NV_optimus=non_NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=iHD VDPAU_DRIVER="" "${@:2}" ;;
+				 *) echo "$Warn_Invalid" ;;
+	esac
+	if [[ ! "${@:2}" ]]; then exit 1; fi
 else
 	GPU="$(basename $0)"
-	cmd="$@"
+	case "$GPU" in
+		  elnvidiad|nvidia) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __VK_LAYER_NV_optimus=NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json __GLX_VENDOR_LIBRARY_NAME=nvidia LIBVA_DRIVER_NAME=nvidia VDPAU_DRIVER=nvidia "$@" ;;
+		elnouveaud|nouveau) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __VK_LAYER_NV_optimus=NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nouveau_icd.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=nouveau VDPAU_DRIVER=nvidia "$@" ;;
+			elamdd|amd) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=0 __VK_LAYER_NV_optimus=non_NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=radeon VDPAU_DRIVER=r600 "$@" ;;
+		    elinteli|intel) DRI_PRIME=0 __NV_PRIME_RENDER_OFFLOAD=0 __VK_LAYER_NV_optimus=non_NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=iHD VDPAU_DRIVER="" "$@" ;;
+				 *) echo "$Warn_Invalid" ;;
+	esac
+	if [[ ! "$@" ]]; then exit 1; fi
 fi
-if [[ ! "$cmd" ]]; then exit 1; fi
-case "$GPU" in
-	  elnvidiad|nvidia) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __VK_LAYER_NV_optimus=NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json __GLX_VENDOR_LIBRARY_NAME=nvidia LIBVA_DRIVER_NAME=nvidia VDPAU_DRIVER=nvidia "$cmd" ;;
-	elnouveaud|nouveau) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __VK_LAYER_NV_optimus=NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nouveau_icd.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=nouveau VDPAU_DRIVER=nvidia "$cmd" ;;
-		elamdd|amd) DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=0 __VK_LAYER_NV_optimus=non_NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=radeon VDPAU_DRIVER=r600 "$cmd" ;;
-	    elinteli|intel) DRI_PRIME=0 __NV_PRIME_RENDER_OFFLOAD=0 __VK_LAYER_NV_optimus=non_NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json:/usr/share/vulkan/icd.d/intel_icd.i686.json __GLX_VENDOR_LIBRARY_NAME=mesa LIBVA_DRIVER_NAME=iHD VDPAU_DRIVER="" "$cmd" ;;
-			 *) echo "$Warn_Invalid" ;;
-esac
